// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_rpc.proto

#include "internal_rpc.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace omnibox {
}  // namespace omnibox
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_internal_5frpc_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* file_level_service_descriptors_internal_5frpc_2eproto[4];
const uint32_t TableStruct_internal_5frpc_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_internal_5frpc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022internal_rpc.proto\022\007omnibox\032\020server_ms"
  "g.proto2\212\001\n\014LoginService\0226\n\005Login\022\025.omni"
  "box.LoginRequest\032\026.omnibox.LoginResponse"
  "\022B\n\tHeartbeat\022\031.omnibox.HeartbeatRequest"
  "\032\032.omnibox.HeartbeatResponse2Z\n\016GatewayS"
  "ervice\022H\n\013PushMessage\022\033.omnibox.PushMess"
  "ageRequest\032\034.omnibox.PushMessageResponse"
  "2\275\003\n\013MetaService\022K\n\014CreateFolder\022\034.omnib"
  "ox.CreateFolderRequest\032\035.omnibox.CreateF"
  "olderResponse\022E\n\nDeleteNode\022\032.omnibox.De"
  "leteNodeRequest\032\033.omnibox.DeleteNodeResp"
  "onse\022B\n\tCheckFile\022\031.omnibox.CheckFileReq"
  "uest\032\032.omnibox.CheckFileResponse\022E\n\nRena"
  "meNode\022\032.omnibox.RenameNodeRequest\032\033.omn"
  "ibox.RenameNodeResponse\022\?\n\010MoveNode\022\030.om"
  "nibox.MoveNodeRequest\032\031.omnibox.MoveNode"
  "Response\022N\n\rListDirectory\022\035.omnibox.List"
  "DirectoryRequest\032\036.omnibox.ListDirectory"
  "Response2c\n\017TransferService\022P\n\013UploadChu"
  "nk\022\037.omnibox.FileChunkUploadRequest\032 .om"
  "nibox.FileChunkUploadResponseB\003\200\001\001b\006prot"
  "o3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_internal_5frpc_2eproto_deps[1] = {
  &::descriptor_table_server_5fmsg_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_internal_5frpc_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_internal_5frpc_2eproto = {
  false, false, 842, descriptor_table_protodef_internal_5frpc_2eproto, "internal_rpc.proto", 
  &descriptor_table_internal_5frpc_2eproto_once, descriptor_table_internal_5frpc_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_internal_5frpc_2eproto::offsets,
  nullptr, file_level_enum_descriptors_internal_5frpc_2eproto, file_level_service_descriptors_internal_5frpc_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_internal_5frpc_2eproto_getter() {
  return &descriptor_table_internal_5frpc_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_internal_5frpc_2eproto(&descriptor_table_internal_5frpc_2eproto);
namespace omnibox {

// ===================================================================

LoginService::~LoginService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* LoginService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_internal_5frpc_2eproto);
  return file_level_service_descriptors_internal_5frpc_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* LoginService::GetDescriptor() {
  return descriptor();
}

void LoginService::Login(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::LoginRequest*,
                         ::omnibox::LoginResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Login() not implemented.");
  done->Run();
}

void LoginService::Heartbeat(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::HeartbeatRequest*,
                         ::omnibox::HeartbeatResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Heartbeat() not implemented.");
  done->Run();
}

void LoginService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_internal_5frpc_2eproto[0]);
  switch(method->index()) {
    case 0:
      Login(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::LoginRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::LoginResponse*>(
                 response),
             done);
      break;
    case 1:
      Heartbeat(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::HeartbeatRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::HeartbeatResponse*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& LoginService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::omnibox::LoginRequest::default_instance();
    case 1:
      return ::omnibox::HeartbeatRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& LoginService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::omnibox::LoginResponse::default_instance();
    case 1:
      return ::omnibox::HeartbeatResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

LoginService_Stub::LoginService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
LoginService_Stub::LoginService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
LoginService_Stub::~LoginService_Stub() {
  if (owns_channel_) delete channel_;
}

void LoginService_Stub::Login(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::LoginRequest* request,
                              ::omnibox::LoginResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void LoginService_Stub::Heartbeat(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::HeartbeatRequest* request,
                              ::omnibox::HeartbeatResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
// ===================================================================

GatewayService::~GatewayService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GatewayService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_internal_5frpc_2eproto);
  return file_level_service_descriptors_internal_5frpc_2eproto[1];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GatewayService::GetDescriptor() {
  return descriptor();
}

void GatewayService::PushMessage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::PushMessageRequest*,
                         ::omnibox::PushMessageResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method PushMessage() not implemented.");
  done->Run();
}

void GatewayService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_internal_5frpc_2eproto[1]);
  switch(method->index()) {
    case 0:
      PushMessage(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::PushMessageRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::PushMessageResponse*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& GatewayService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::omnibox::PushMessageRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& GatewayService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::omnibox::PushMessageResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

GatewayService_Stub::GatewayService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
GatewayService_Stub::GatewayService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
GatewayService_Stub::~GatewayService_Stub() {
  if (owns_channel_) delete channel_;
}

void GatewayService_Stub::PushMessage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::PushMessageRequest* request,
                              ::omnibox::PushMessageResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
// ===================================================================

MetaService::~MetaService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* MetaService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_internal_5frpc_2eproto);
  return file_level_service_descriptors_internal_5frpc_2eproto[2];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* MetaService::GetDescriptor() {
  return descriptor();
}

void MetaService::CreateFolder(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::CreateFolderRequest*,
                         ::omnibox::CreateFolderResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method CreateFolder() not implemented.");
  done->Run();
}

void MetaService::DeleteNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::DeleteNodeRequest*,
                         ::omnibox::DeleteNodeResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method DeleteNode() not implemented.");
  done->Run();
}

void MetaService::CheckFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::CheckFileRequest*,
                         ::omnibox::CheckFileResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method CheckFile() not implemented.");
  done->Run();
}

void MetaService::RenameNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::RenameNodeRequest*,
                         ::omnibox::RenameNodeResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method RenameNode() not implemented.");
  done->Run();
}

void MetaService::MoveNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::MoveNodeRequest*,
                         ::omnibox::MoveNodeResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method MoveNode() not implemented.");
  done->Run();
}

void MetaService::ListDirectory(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::ListDirectoryRequest*,
                         ::omnibox::ListDirectoryResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method ListDirectory() not implemented.");
  done->Run();
}

void MetaService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_internal_5frpc_2eproto[2]);
  switch(method->index()) {
    case 0:
      CreateFolder(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::CreateFolderRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::CreateFolderResponse*>(
                 response),
             done);
      break;
    case 1:
      DeleteNode(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::DeleteNodeRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::DeleteNodeResponse*>(
                 response),
             done);
      break;
    case 2:
      CheckFile(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::CheckFileRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::CheckFileResponse*>(
                 response),
             done);
      break;
    case 3:
      RenameNode(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::RenameNodeRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::RenameNodeResponse*>(
                 response),
             done);
      break;
    case 4:
      MoveNode(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::MoveNodeRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::MoveNodeResponse*>(
                 response),
             done);
      break;
    case 5:
      ListDirectory(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::ListDirectoryRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::ListDirectoryResponse*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& MetaService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::omnibox::CreateFolderRequest::default_instance();
    case 1:
      return ::omnibox::DeleteNodeRequest::default_instance();
    case 2:
      return ::omnibox::CheckFileRequest::default_instance();
    case 3:
      return ::omnibox::RenameNodeRequest::default_instance();
    case 4:
      return ::omnibox::MoveNodeRequest::default_instance();
    case 5:
      return ::omnibox::ListDirectoryRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& MetaService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::omnibox::CreateFolderResponse::default_instance();
    case 1:
      return ::omnibox::DeleteNodeResponse::default_instance();
    case 2:
      return ::omnibox::CheckFileResponse::default_instance();
    case 3:
      return ::omnibox::RenameNodeResponse::default_instance();
    case 4:
      return ::omnibox::MoveNodeResponse::default_instance();
    case 5:
      return ::omnibox::ListDirectoryResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

MetaService_Stub::MetaService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
MetaService_Stub::MetaService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
MetaService_Stub::~MetaService_Stub() {
  if (owns_channel_) delete channel_;
}

void MetaService_Stub::CreateFolder(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::CreateFolderRequest* request,
                              ::omnibox::CreateFolderResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void MetaService_Stub::DeleteNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::DeleteNodeRequest* request,
                              ::omnibox::DeleteNodeResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void MetaService_Stub::CheckFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::CheckFileRequest* request,
                              ::omnibox::CheckFileResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}
void MetaService_Stub::RenameNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::RenameNodeRequest* request,
                              ::omnibox::RenameNodeResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(3),
                       controller, request, response, done);
}
void MetaService_Stub::MoveNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::MoveNodeRequest* request,
                              ::omnibox::MoveNodeResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(4),
                       controller, request, response, done);
}
void MetaService_Stub::ListDirectory(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::ListDirectoryRequest* request,
                              ::omnibox::ListDirectoryResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(5),
                       controller, request, response, done);
}
// ===================================================================

TransferService::~TransferService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* TransferService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_internal_5frpc_2eproto);
  return file_level_service_descriptors_internal_5frpc_2eproto[3];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* TransferService::GetDescriptor() {
  return descriptor();
}

void TransferService::UploadChunk(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::omnibox::FileChunkUploadRequest*,
                         ::omnibox::FileChunkUploadResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method UploadChunk() not implemented.");
  done->Run();
}

void TransferService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_internal_5frpc_2eproto[3]);
  switch(method->index()) {
    case 0:
      UploadChunk(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::omnibox::FileChunkUploadRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::omnibox::FileChunkUploadResponse*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& TransferService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::omnibox::FileChunkUploadRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& TransferService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::omnibox::FileChunkUploadResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

TransferService_Stub::TransferService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
TransferService_Stub::TransferService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
TransferService_Stub::~TransferService_Stub() {
  if (owns_channel_) delete channel_;
}

void TransferService_Stub::UploadChunk(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::omnibox::FileChunkUploadRequest* request,
                              ::omnibox::FileChunkUploadResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace omnibox
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
