// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_rpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_internal_5frpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_internal_5frpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include "server_msg.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_internal_5frpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_internal_5frpc_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_internal_5frpc_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace omnibox {

// ===================================================================


// ===================================================================

class LoginService_Stub;

class LoginService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline LoginService() {};
 public:
  virtual ~LoginService();

  typedef LoginService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void Login(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::LoginRequest* request,
                       ::omnibox::LoginResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void Heartbeat(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::HeartbeatRequest* request,
                       ::omnibox::HeartbeatResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(LoginService);
};

class LoginService_Stub : public LoginService {
 public:
  LoginService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  LoginService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~LoginService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements LoginService ------------------------------------------

  void Login(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::LoginRequest* request,
                       ::omnibox::LoginResponse* response,
                       ::google::protobuf::Closure* done);
  void Heartbeat(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::HeartbeatRequest* request,
                       ::omnibox::HeartbeatResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(LoginService_Stub);
};


// -------------------------------------------------------------------

class GatewayService_Stub;

class GatewayService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline GatewayService() {};
 public:
  virtual ~GatewayService();

  typedef GatewayService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void PushMessage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::PushMessageRequest* request,
                       ::omnibox::PushMessageResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GatewayService);
};

class GatewayService_Stub : public GatewayService {
 public:
  GatewayService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  GatewayService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~GatewayService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements GatewayService ------------------------------------------

  void PushMessage(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::PushMessageRequest* request,
                       ::omnibox::PushMessageResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GatewayService_Stub);
};


// -------------------------------------------------------------------

class MetaService_Stub;

class MetaService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline MetaService() {};
 public:
  virtual ~MetaService();

  typedef MetaService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void CreateFolder(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::CreateFolderRequest* request,
                       ::omnibox::CreateFolderResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void DeleteNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::DeleteNodeRequest* request,
                       ::omnibox::DeleteNodeResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void CheckFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::CheckFileRequest* request,
                       ::omnibox::CheckFileResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void RenameNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::RenameNodeRequest* request,
                       ::omnibox::RenameNodeResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void MoveNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::MoveNodeRequest* request,
                       ::omnibox::MoveNodeResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void ListDirectory(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::ListDirectoryRequest* request,
                       ::omnibox::ListDirectoryResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(MetaService);
};

class MetaService_Stub : public MetaService {
 public:
  MetaService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  MetaService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~MetaService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements MetaService ------------------------------------------

  void CreateFolder(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::CreateFolderRequest* request,
                       ::omnibox::CreateFolderResponse* response,
                       ::google::protobuf::Closure* done);
  void DeleteNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::DeleteNodeRequest* request,
                       ::omnibox::DeleteNodeResponse* response,
                       ::google::protobuf::Closure* done);
  void CheckFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::CheckFileRequest* request,
                       ::omnibox::CheckFileResponse* response,
                       ::google::protobuf::Closure* done);
  void RenameNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::RenameNodeRequest* request,
                       ::omnibox::RenameNodeResponse* response,
                       ::google::protobuf::Closure* done);
  void MoveNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::MoveNodeRequest* request,
                       ::omnibox::MoveNodeResponse* response,
                       ::google::protobuf::Closure* done);
  void ListDirectory(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::ListDirectoryRequest* request,
                       ::omnibox::ListDirectoryResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(MetaService_Stub);
};


// -------------------------------------------------------------------

class TransferService_Stub;

class TransferService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline TransferService() {};
 public:
  virtual ~TransferService();

  typedef TransferService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void UploadChunk(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::FileChunkUploadRequest* request,
                       ::omnibox::FileChunkUploadResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(TransferService);
};

class TransferService_Stub : public TransferService {
 public:
  TransferService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  TransferService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~TransferService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements TransferService ------------------------------------------

  void UploadChunk(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::omnibox::FileChunkUploadRequest* request,
                       ::omnibox::FileChunkUploadResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(TransferService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace omnibox

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_internal_5frpc_2eproto
