// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf C++ Version: 5.29.3

#include "common.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ServerApi {

inline constexpr PacketHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        seq_id_{::uint64_t{0u}},
        msg_id_{static_cast< ::ServerApi::MsgId >(0)},
        error_code_{static_cast< ::ServerApi::ErrorCode >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PacketHeader::PacketHeader(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PacketHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketHeaderDefaultTypeInternal() {}
  union {
    PacketHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketHeaderDefaultTypeInternal _PacketHeader_default_instance_;
}  // namespace ServerApi
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_common_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_common_2eproto = nullptr;
const ::uint32_t
    TableStruct_common_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ServerApi::PacketHeader, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ServerApi::PacketHeader, _impl_.msg_id_),
        PROTOBUF_FIELD_OFFSET(::ServerApi::PacketHeader, _impl_.seq_id_),
        PROTOBUF_FIELD_OFFSET(::ServerApi::PacketHeader, _impl_.error_code_),
        PROTOBUF_FIELD_OFFSET(::ServerApi::PacketHeader, _impl_.error_msg_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ServerApi::PacketHeader)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::ServerApi::_PacketHeader_default_instance_._instance,
};
const char descriptor_table_protodef_common_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014common.proto\022\tServerApi\"}\n\014PacketHeade"
    "r\022 \n\006msg_id\030\001 \001(\0162\020.ServerApi.MsgId\022\016\n\006s"
    "eq_id\030\002 \001(\004\022(\n\nerror_code\030\003 \001(\0162\024.Server"
    "Api.ErrorCode\022\021\n\terror_msg\030\004 \001(\t*z\n\005MsgI"
    "d\022\016\n\nID_UNKNOWN\020\000\022\020\n\014ID_HEARTBEAT\020\001\022\021\n\014I"
    "D_LOGIN_REQ\020\351\007\022\021\n\014ID_LOGIN_RSP\020\352\007\022\024\n\017ID_"
    "SCREEN_FRAME\020\321\017\022\023\n\016ID_CONTROL_CMD\020\322\017*y\n\t"
    "ErrorCode\022\017\n\013ERR_SUCCESS\020\000\022\027\n\023ERR_SERVER"
    "_INTERNAL\020\001\022\021\n\rERR_WRONG_PWD\020\002\022\026\n\022ERR_AC"
    "COUNT_IN_USE\020\003\022\027\n\023ERR_ACCOUNT_EXPIRED\020\004*"
    ";\n\010FileType\022\020\n\014FILE_UNKNOWN\020\000\022\016\n\nFILE_MO"
    "VIE\020\001\022\r\n\tFILE_GAME\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_common_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_common_2eproto = {
    false,
    false,
    468,
    descriptor_table_protodef_common_2eproto,
    "common.proto",
    &descriptor_table_common_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_common_2eproto::offsets,
    file_level_enum_descriptors_common_2eproto,
    file_level_service_descriptors_common_2eproto,
};
namespace ServerApi {
const ::google::protobuf::EnumDescriptor* MsgId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_common_2eproto);
  return file_level_enum_descriptors_common_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MsgId_internal_data_[] = {
    131072u, 262144u, 2001u, 1002u, 2002u, 1001u, };
bool MsgId_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, MsgId_internal_data_);
}
const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_common_2eproto);
  return file_level_enum_descriptors_common_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t ErrorCode_internal_data_[] = {
    327680u, 0u, };
bool ErrorCode_IsValid(int value) {
  return 0 <= value && value <= 4;
}
const ::google::protobuf::EnumDescriptor* FileType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_common_2eproto);
  return file_level_enum_descriptors_common_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t FileType_internal_data_[] = {
    196608u, 0u, };
bool FileType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class PacketHeader::_Internal {
 public:
};

PacketHeader::PacketHeader(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ServerApi.PacketHeader)
}
inline PROTOBUF_NDEBUG_INLINE PacketHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ServerApi::PacketHeader& from_msg)
      : error_msg_(arena, from.error_msg_),
        _cached_size_{0} {}

PacketHeader::PacketHeader(
    ::google::protobuf::Arena* arena,
    const PacketHeader& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PacketHeader* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, seq_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, seq_id_),
           offsetof(Impl_, error_code_) -
               offsetof(Impl_, seq_id_) +
               sizeof(Impl_::error_code_));

  // @@protoc_insertion_point(copy_constructor:ServerApi.PacketHeader)
}
inline PROTOBUF_NDEBUG_INLINE PacketHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : error_msg_(arena),
        _cached_size_{0} {}

inline void PacketHeader::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, seq_id_),
           0,
           offsetof(Impl_, error_code_) -
               offsetof(Impl_, seq_id_) +
               sizeof(Impl_::error_code_));
}
PacketHeader::~PacketHeader() {
  // @@protoc_insertion_point(destructor:ServerApi.PacketHeader)
  SharedDtor(*this);
}
inline void PacketHeader::SharedDtor(MessageLite& self) {
  PacketHeader& this_ = static_cast<PacketHeader&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.error_msg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PacketHeader::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PacketHeader(arena);
}
constexpr auto PacketHeader::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PacketHeader),
                                            alignof(PacketHeader));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PacketHeader::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PacketHeader_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PacketHeader::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PacketHeader>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PacketHeader::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PacketHeader>(), &PacketHeader::ByteSizeLong,
            &PacketHeader::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_._cached_size_),
        false,
    },
    &PacketHeader::kDescriptorMethods,
    &descriptor_table_common_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PacketHeader::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 40, 2> PacketHeader::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ServerApi::PacketHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error_msg = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.error_msg_)}},
    // .ServerApi.MsgId msg_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketHeader, _impl_.msg_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.msg_id_)}},
    // uint64 seq_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PacketHeader, _impl_.seq_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.seq_id_)}},
    // .ServerApi.ErrorCode error_code = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketHeader, _impl_.error_code_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.error_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .ServerApi.MsgId msg_id = 1;
    {PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.msg_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint64 seq_id = 2;
    {PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.seq_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // .ServerApi.ErrorCode error_code = 3;
    {PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.error_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string error_msg = 4;
    {PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.error_msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\0\0\0\11\0\0\0"
    "ServerApi.PacketHeader"
    "error_msg"
  }},
};

PROTOBUF_NOINLINE void PacketHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:ServerApi.PacketHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_msg_.ClearToEmpty();
  ::memset(&_impl_.seq_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.error_code_) -
      reinterpret_cast<char*>(&_impl_.seq_id_)) + sizeof(_impl_.error_code_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PacketHeader::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PacketHeader& this_ = static_cast<const PacketHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PacketHeader::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PacketHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ServerApi.PacketHeader)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .ServerApi.MsgId msg_id = 1;
          if (this_._internal_msg_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_msg_id(), target);
          }

          // uint64 seq_id = 2;
          if (this_._internal_seq_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_seq_id(), target);
          }

          // .ServerApi.ErrorCode error_code = 3;
          if (this_._internal_error_code() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_error_code(), target);
          }

          // string error_msg = 4;
          if (!this_._internal_error_msg().empty()) {
            const std::string& _s = this_._internal_error_msg();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ServerApi.PacketHeader.error_msg");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ServerApi.PacketHeader)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PacketHeader::ByteSizeLong(const MessageLite& base) {
          const PacketHeader& this_ = static_cast<const PacketHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PacketHeader::ByteSizeLong() const {
          const PacketHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ServerApi.PacketHeader)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string error_msg = 4;
            if (!this_._internal_error_msg().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error_msg());
            }
            // uint64 seq_id = 2;
            if (this_._internal_seq_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_seq_id());
            }
            // .ServerApi.MsgId msg_id = 1;
            if (this_._internal_msg_id() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_msg_id());
            }
            // .ServerApi.ErrorCode error_code = 3;
            if (this_._internal_error_code() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_error_code());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PacketHeader::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PacketHeader*>(&to_msg);
  auto& from = static_cast<const PacketHeader&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ServerApi.PacketHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_msg().empty()) {
    _this->_internal_set_error_msg(from._internal_error_msg());
  }
  if (from._internal_seq_id() != 0) {
    _this->_impl_.seq_id_ = from._impl_.seq_id_;
  }
  if (from._internal_msg_id() != 0) {
    _this->_impl_.msg_id_ = from._impl_.msg_id_;
  }
  if (from._internal_error_code() != 0) {
    _this->_impl_.error_code_ = from._impl_.error_code_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PacketHeader::CopyFrom(const PacketHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ServerApi.PacketHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PacketHeader::InternalSwap(PacketHeader* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_msg_, &other->_impl_.error_msg_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.error_code_)
      + sizeof(PacketHeader::_impl_.error_code_)
      - PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.seq_id_)>(
          reinterpret_cast<char*>(&_impl_.seq_id_),
          reinterpret_cast<char*>(&other->_impl_.seq_id_));
}

::google::protobuf::Metadata PacketHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ServerApi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_common_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
