// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf C++ Version: 5.29.3

#ifndef common_2eproto_2epb_2eh
#define common_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_common_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_common_2eproto;
namespace ServerApi {
class PacketHeader;
struct PacketHeaderDefaultTypeInternal;
extern PacketHeaderDefaultTypeInternal _PacketHeader_default_instance_;
}  // namespace ServerApi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ServerApi {
enum MsgId : int {
  ID_UNKNOWN = 0,
  ID_HEARTBEAT = 1,
  ID_LOGIN_REQ = 1001,
  ID_LOGIN_RSP = 1002,
  ID_SCREEN_FRAME = 2001,
  ID_CONTROL_CMD = 2002,
  MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool MsgId_IsValid(int value);
extern const uint32_t MsgId_internal_data_[];
constexpr MsgId MsgId_MIN = static_cast<MsgId>(0);
constexpr MsgId MsgId_MAX = static_cast<MsgId>(2002);
constexpr int MsgId_ARRAYSIZE = 2002 + 1;
const ::google::protobuf::EnumDescriptor*
MsgId_descriptor();
template <typename T>
const std::string& MsgId_Name(T value) {
  static_assert(std::is_same<T, MsgId>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MsgId_Name().");
  return ::google::protobuf::internal::NameOfEnum(MsgId_descriptor(), value);
}
inline bool MsgId_Parse(absl::string_view name, MsgId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgId>(
      MsgId_descriptor(), name, value);
}
enum ErrorCode : int {
  ERR_SUCCESS = 0,
  ERR_SERVER_INTERNAL = 1,
  ERR_WRONG_PWD = 2,
  ERR_ACCOUNT_IN_USE = 3,
  ERR_ACCOUNT_EXPIRED = 4,
  ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ErrorCode_IsValid(int value);
extern const uint32_t ErrorCode_internal_data_[];
constexpr ErrorCode ErrorCode_MIN = static_cast<ErrorCode>(0);
constexpr ErrorCode ErrorCode_MAX = static_cast<ErrorCode>(4);
constexpr int ErrorCode_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
ErrorCode_descriptor();
template <typename T>
const std::string& ErrorCode_Name(T value) {
  static_assert(std::is_same<T, ErrorCode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ErrorCode_Name().");
  return ErrorCode_Name(static_cast<ErrorCode>(value));
}
template <>
inline const std::string& ErrorCode_Name(ErrorCode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ErrorCode_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool ErrorCode_Parse(absl::string_view name, ErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ErrorCode>(
      ErrorCode_descriptor(), name, value);
}
enum FileType : int {
  FILE_UNKNOWN = 0,
  FILE_MOVIE = 1,
  FILE_GAME = 2,
  FileType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  FileType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool FileType_IsValid(int value);
extern const uint32_t FileType_internal_data_[];
constexpr FileType FileType_MIN = static_cast<FileType>(0);
constexpr FileType FileType_MAX = static_cast<FileType>(2);
constexpr int FileType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
FileType_descriptor();
template <typename T>
const std::string& FileType_Name(T value) {
  static_assert(std::is_same<T, FileType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to FileType_Name().");
  return FileType_Name(static_cast<FileType>(value));
}
template <>
inline const std::string& FileType_Name(FileType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FileType_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool FileType_Parse(absl::string_view name, FileType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FileType>(
      FileType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class PacketHeader final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ServerApi.PacketHeader) */ {
 public:
  inline PacketHeader() : PacketHeader(nullptr) {}
  ~PacketHeader() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PacketHeader* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PacketHeader));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PacketHeader(
      ::google::protobuf::internal::ConstantInitialized);

  inline PacketHeader(const PacketHeader& from) : PacketHeader(nullptr, from) {}
  inline PacketHeader(PacketHeader&& from) noexcept
      : PacketHeader(nullptr, std::move(from)) {}
  inline PacketHeader& operator=(const PacketHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline PacketHeader& operator=(PacketHeader&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PacketHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const PacketHeader* internal_default_instance() {
    return reinterpret_cast<const PacketHeader*>(
        &_PacketHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PacketHeader& a, PacketHeader& b) { a.Swap(&b); }
  inline void Swap(PacketHeader* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PacketHeader* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PacketHeader* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PacketHeader>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PacketHeader& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PacketHeader& from) { PacketHeader::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PacketHeader* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ServerApi.PacketHeader"; }

 protected:
  explicit PacketHeader(::google::protobuf::Arena* arena);
  PacketHeader(::google::protobuf::Arena* arena, const PacketHeader& from);
  PacketHeader(::google::protobuf::Arena* arena, PacketHeader&& from) noexcept
      : PacketHeader(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrorMsgFieldNumber = 4,
    kSeqIdFieldNumber = 2,
    kMsgIdFieldNumber = 1,
    kErrorCodeFieldNumber = 3,
  };
  // string error_msg = 4;
  void clear_error_msg() ;
  const std::string& error_msg() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_error_msg(Arg_&& arg, Args_... args);
  std::string* mutable_error_msg();
  PROTOBUF_NODISCARD std::string* release_error_msg();
  void set_allocated_error_msg(std::string* value);

  private:
  const std::string& _internal_error_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_msg(
      const std::string& value);
  std::string* _internal_mutable_error_msg();

  public:
  // uint64 seq_id = 2;
  void clear_seq_id() ;
  ::uint64_t seq_id() const;
  void set_seq_id(::uint64_t value);

  private:
  ::uint64_t _internal_seq_id() const;
  void _internal_set_seq_id(::uint64_t value);

  public:
  // .ServerApi.MsgId msg_id = 1;
  void clear_msg_id() ;
  ::ServerApi::MsgId msg_id() const;
  void set_msg_id(::ServerApi::MsgId value);

  private:
  ::ServerApi::MsgId _internal_msg_id() const;
  void _internal_set_msg_id(::ServerApi::MsgId value);

  public:
  // .ServerApi.ErrorCode error_code = 3;
  void clear_error_code() ;
  ::ServerApi::ErrorCode error_code() const;
  void set_error_code(::ServerApi::ErrorCode value);

  private:
  ::ServerApi::ErrorCode _internal_error_code() const;
  void _internal_set_error_code(::ServerApi::ErrorCode value);

  public:
  // @@protoc_insertion_point(class_scope:ServerApi.PacketHeader)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      40, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PacketHeader& from_msg);
    ::google::protobuf::internal::ArenaStringPtr error_msg_;
    ::uint64_t seq_id_;
    int msg_id_;
    int error_code_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PacketHeader

// .ServerApi.MsgId msg_id = 1;
inline void PacketHeader::clear_msg_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_id_ = 0;
}
inline ::ServerApi::MsgId PacketHeader::msg_id() const {
  // @@protoc_insertion_point(field_get:ServerApi.PacketHeader.msg_id)
  return _internal_msg_id();
}
inline void PacketHeader::set_msg_id(::ServerApi::MsgId value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:ServerApi.PacketHeader.msg_id)
}
inline ::ServerApi::MsgId PacketHeader::_internal_msg_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::ServerApi::MsgId>(_impl_.msg_id_);
}
inline void PacketHeader::_internal_set_msg_id(::ServerApi::MsgId value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_id_ = value;
}

// uint64 seq_id = 2;
inline void PacketHeader::clear_seq_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_id_ = ::uint64_t{0u};
}
inline ::uint64_t PacketHeader::seq_id() const {
  // @@protoc_insertion_point(field_get:ServerApi.PacketHeader.seq_id)
  return _internal_seq_id();
}
inline void PacketHeader::set_seq_id(::uint64_t value) {
  _internal_set_seq_id(value);
  // @@protoc_insertion_point(field_set:ServerApi.PacketHeader.seq_id)
}
inline ::uint64_t PacketHeader::_internal_seq_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seq_id_;
}
inline void PacketHeader::_internal_set_seq_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_id_ = value;
}

// .ServerApi.ErrorCode error_code = 3;
inline void PacketHeader::clear_error_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_code_ = 0;
}
inline ::ServerApi::ErrorCode PacketHeader::error_code() const {
  // @@protoc_insertion_point(field_get:ServerApi.PacketHeader.error_code)
  return _internal_error_code();
}
inline void PacketHeader::set_error_code(::ServerApi::ErrorCode value) {
  _internal_set_error_code(value);
  // @@protoc_insertion_point(field_set:ServerApi.PacketHeader.error_code)
}
inline ::ServerApi::ErrorCode PacketHeader::_internal_error_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::ServerApi::ErrorCode>(_impl_.error_code_);
}
inline void PacketHeader::_internal_set_error_code(::ServerApi::ErrorCode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_code_ = value;
}

// string error_msg = 4;
inline void PacketHeader::clear_error_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_msg_.ClearToEmpty();
}
inline const std::string& PacketHeader::error_msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ServerApi.PacketHeader.error_msg)
  return _internal_error_msg();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PacketHeader::set_error_msg(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ServerApi.PacketHeader.error_msg)
}
inline std::string* PacketHeader::mutable_error_msg() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_error_msg();
  // @@protoc_insertion_point(field_mutable:ServerApi.PacketHeader.error_msg)
  return _s;
}
inline const std::string& PacketHeader::_internal_error_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_msg_.Get();
}
inline void PacketHeader::_internal_set_error_msg(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_msg_.Set(value, GetArena());
}
inline std::string* PacketHeader::_internal_mutable_error_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.error_msg_.Mutable( GetArena());
}
inline std::string* PacketHeader::release_error_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ServerApi.PacketHeader.error_msg)
  return _impl_.error_msg_.Release();
}
inline void PacketHeader::set_allocated_error_msg(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_msg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.error_msg_.IsDefault()) {
    _impl_.error_msg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ServerApi.PacketHeader.error_msg)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ServerApi


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ServerApi::MsgId> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ServerApi::MsgId>() {
  return ::ServerApi::MsgId_descriptor();
}
template <>
struct is_proto_enum<::ServerApi::ErrorCode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ServerApi::ErrorCode>() {
  return ::ServerApi::ErrorCode_descriptor();
}
template <>
struct is_proto_enum<::ServerApi::FileType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::ServerApi::FileType>() {
  return ::ServerApi::FileType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // common_2eproto_2epb_2eh
